### ISSUE TITLE
Auto play is not allowed on Chrome https://goo.gl/7K7WLu

### ISSUE THREAD

**Issue by KatherineWinter** [cutterbl/CDGPlayer#1]

**Comment by cutterbl** [comment]
@KatherineWinter I finally got around to implementing your changes (sorry it took so long). Thanks for the assist. Still odd you can't submit a PR. I have to figure that out.

I'm seeing your work on JMPerez/karaoke. I'm wondering if there's a way to integrate at some point...

**Comment by cutterbl** [comment]
@KatherineWinter  could you resend your email to me again? Provider dropped the message before I could respond.

**Comment by KatherineWinter** [comment]
> @KatherineWinter could you resend your email to me again? Provider dropped the message before I could respond.

Hi Cutter,

I saw your response. Im glad to hear my collaboration was helpful!

As far as PRs, I haven’t been able to figure out why GitHub won’t let me submit PRs. I can’t do it on any repos (apart from work). I wonder if it has something to do with the explicit “collaborator” repo status? Shrug. GitHub  doesnt mention anything about that in their docs.

As far as my fork of JM Perez’s stuff, what kind of integration would inspire you?

I have a few karaoke projects in the works that maybe we can tie together. That would be fun.

I was admiring your CGD reading code. Very clean. 
From your experience of writing that, do you know the exact format for creating those files? It would be cool to create a “CGD maker”. I was trying to reverse engineer the format, but I decided I like “enhanced LRC” better from how simple it is.  What made you decide to go the CGD route? 

Happy holidays!
