### ISSUE TITLE
CDG Fonts

### ISSUE THREAD

**Issue by oasiz** [cutterbl/CDGPlayer#27]
Hi, hope you're well.

I've just loaded this up in a localhost and added a Mr Entertainer zip file and it works great, good job!

I don't know much about CDG files and if they're editable etc but on my (MacBook) computer the lyrics are quite blocky/pixellated - presumably because my screen is quite a high resolution.

I see the canvas is set to 300x216 - would making that bigger help, or would the actual CDG file need to be edited?

I'm hoping to have better control over the quality of the images/text shown on screen and just wondered what (if anything) could be done to improve this?

Many thanks for your help.

Rob

**Comment by cutterbl** [comment]
@oasiz CDG graphics can vary according to the the producer (SoundChoice, Karaoke Version, Chartbusters, etc), and don't always scale well to higher resolutions. I do plan to dive deeper on the output, but honestly not huge priority right now. Sort of a pet project sorta thing.

**Comment by oasiz** [comment]
@cutterbl Thanks for that - apologies I hadn't been notified about your reply!

Yes I've tried a few different ones, the same as you've mentioned plus Sunfly and they're all pretty poor quality unfortunately.

I'd love to find a way to improve this. Vector graphics possibly?

A way of extracting the lyrics and timing would be ideal, for a custom screen...

Appreciate you looking at this, hopefully there's a way to improve the output.


Rob

**Comment by cutterbl** [comment]
@oasiz Yeah, I wish that was possible too. 'CDG' is a generic term for 'Compact Disc plus Graphics'. What we have here is a two file system that a) plays an MP3 file and b) decodes and displays the graphics data in a file with a '.cdg' extension. These two files are enclosed in a zip file, for optimal compression. The '.cdg' file is byte code representation of the graphics the particular producer timed to associate with the audio. They don't contain the raw lyrics as text, but rather the bits that make up the 'video' display (basically think of a huge animated gif scenario), so there really is no way of extracting the lyrics and applying a more kernel safe font to them to improve the output. Most cdg producers originally formatted to a small screen (typically an analog tv connected to a karaoke machine via an RG6 cable), so upscaling the image can appear pretty pixelated. More recent producers use a better approach for larger format, but can still have the same effect on very large displays.
